export const SLIDER_CHANGE = 'SLIDER_CHANGE';
export const RATE_DAMAGE_SELECT = 'RATE_DAMAGE_SELECT';
export const CALCULATE_RATE = 'CALCULATE_RATE';
export const SAVE_POLICY_DETAILS = 'SAVE_POLICY_DETAILS';
export const SUMMARY_HOVER = 'SUMMARY_HOVER';